#ifndef __SLAM_INCLUDES__
#define __SLAM_INCLUDES__
#include <all.h>
#include <any.h>
#include <Att_pred.h>
#include <Att_upd.h>
#include <blkdiag.h>
#include <Ch_dn_To_h_un.h>
#include <colon.h>
#include <cross.h>
#include <diag.h>
#include <eig.h>
#include <eye.h>
#include <fileManager.h>
#include <fprintf.h>
#include <getH_R_res.h>
#include <getMap.h>
#include <initializePoint.h>
#include <kron.h>
#include <Mahalanobis_EKF.h>
#include <mrdivide.h>
#include <norm.h>
#include <predictMeasurement_left.h>
#include <predictMeasurement_stereo.h>
#include <QuatFromRotJ.h>
#include <quatmultJ.h>
#include <quatPlusThetaJ.h>
#include <rdivide.h>
#include <repmat.h>
#include <rt_defines.h>
#include <rtGetInf.h>
#include <rtGetNaN.h>
#include <rt_nonfinite.h>
#include <rtwtypes.h>
#include <SLAM_data.h>
#include <SLAM_emxAPI.h>
#include <SLAM_emxutil.h>
#include <SLAM.h>
#include <SLAM_includes.h>
#include <SLAM_initialize.h>
#include <SLAM_pred_model.h>
#include <SLAM_rtwutil.h>
#include <SLAM_terminate.h>
#include <SLAM_types.h>
#include <SLAM_updIT.h>
#include <sqrt.h>
#include <squeeze.h>
#include <sum.h>
#include <svd.h>
#endif
