#ifndef __SLAM_INCLUDES__
#define __SLAM_INCLUDES__
#include <any.h>
#include <colon.h>
#include <det.h>
#include <diag.h>
#include <eye.h>
#include <fileManager.h>
#include <fprintf.h>
#include <getCameraParams.h>
#include <getJacobianAndResidual_std.h>
#include <initializePoint.h>
#include <mrdivide.h>
#include <norm.h>
#include <QuatFromRotJ.h>
#include <quatmultJ.h>
#include <quatPlusThetaJ.h>
#include <RotFromQuatJ.h>
#include <rtGetInf.h>
#include <rtGetNaN.h>
#include <rt_nonfinite.h>
#include <rtwtypes.h>
#include <SLAM_data.h>
#include <SLAM_emxAPI.h>
#include <SLAM_emxutil.h>
#include <SLAM.h>
#include <SLAM_includes.h>
#include <SLAM_initialize.h>
#include <SLAM_pred_euler.h>
#include <SLAM_rtwutil.h>
#include <SLAM_terminate.h>
#include <SLAM_types.h>
#include <SLAM_updIT.h>
#include <svd.h>
#endif
